import './components/app'
import './components/header'
import './components/swiper'
import './components/elasticGradient'
import './components/accordion'
import './components/inputFile'
import './components/phone'
import './components/line'
import './components/scrollToAnchor'

import './components//animation/blockCooperation'
import './components//animation/blockReceive'
import './components//animation/blockTrust'
import './components//animation/blockWeUnderstand'
import './components//animation/blockHowPayment'
import './components//animation/blockQuestion'
import './components//animation/blockFooter'
